from decimal import Decimal

from sqlalchemy import Column, BigInteger, Numeric, ForeignKey
from sqlalchemy.orm import relationship

from src.extensions import db

Base = db.Model


class KbaiThreshold(Base):
    """
    KBAI Threshold model

    Maps to kbai.kbai_threshold and exposes KPI/ratio columns generated by pgModeler.
    Only structural mapping is provided here; add business helpers as needed.
    """

    __tablename__ = "kbai_threshold"
    __table_args__ = {"schema": "kbai"}

    # NOTE: Adjust primary key column name if your real schema uses a different one.
    id_threshold = Column(BigInteger, primary_key=True, autoincrement=True)
    
    # Foreign key to kbai_sectors
    id_sector = Column(BigInteger, ForeignKey('kbai.kbai_sectors.id_sector'), nullable=True)
    
    # Relationship to KbaiSector
    sector = relationship('KbaiSector', back_populates='thresholds')

    # Averages
    mol_average = Column(Numeric(14, 2))
    risultato_operativo_average = Column(Numeric(14, 2))
    roe_average = Column(Numeric(14, 2))
    ros_average = Column(Numeric(14, 2))
    roi_average = Column(Numeric(14, 2))
    mol_su_ricavi_average = Column(Numeric(14, 2))
    consumi_su_costi_average = Column(Numeric(14, 2))
    oneri_su_fatturato_average = Column(Numeric(14, 2))
    oneri_su_mol_average = Column(Numeric(14, 2))
    cash_flow_average = Column(Numeric(14, 2))
    indice_liquidita_average = Column(Numeric(14, 2))
    tasso_intensita_average = Column(Numeric(14, 2))
    costi_esterni_su_costi_average = Column(Numeric(14, 2))
    costi_lavoro_su_costi_average = Column(Numeric(14, 2))

    # Min
    mol_min = Column(Numeric(14, 2))
    risultato_operativo_min = Column(Numeric(14, 2))
    cash_flow_min = Column(Numeric(14, 2))
    roe_min = Column(Numeric(14, 2))
    ros_min = Column(Numeric(14, 2))
    roi_min = Column(Numeric(14, 2))
    mol_su_ricavi_min = Column(Numeric(14, 2))
    oneri_su_fatturato_min = Column(Numeric(14, 2))
    oneri_su_mol_min = Column(Numeric(14, 2))
    indice_liquidita_min = Column(Numeric(14, 2))
    tasso_intensita_min = Column(Numeric(14, 2))
    consumi_su_costi_min = Column(Numeric(14, 2))
    costi_esterni_su_costi_min = Column(Numeric(14, 2))
    costi_lavoro_su_costi_min = Column(Numeric(14, 2))

    # Max
    mol_max = Column(Numeric(14, 2))
    risultato_operativo_max = Column(Numeric(14, 2))
    cash_flow_max = Column(Numeric(14, 2))
    roe_max = Column(Numeric(14, 2))
    ros_max = Column(Numeric(14, 2))
    roi_max = Column(Numeric(14, 2))
    mol_su_ricavi_max = Column(Numeric(14, 2))
    oneri_su_fatturato_max = Column(Numeric(14, 2))
    oneri_su_mol_max = Column(Numeric(14, 2))
    indice_liquidita_max = Column(Numeric(14, 2))
    tasso_intensita_max = Column(Numeric(14, 2))
    consumi_su_costi_max = Column(Numeric(14, 2))
    costi_esterni_su_costi_max = Column(Numeric(14, 2))
    costi_lavoro_su_costi_max = Column(Numeric(14, 2))

    # Base KPI components
    ricavi = Column(Numeric(14, 2))
    costi_totali = Column(Numeric(14, 2))
    costi_esterni = Column(Numeric(14, 2))
    consumi_materiale = Column(Numeric(14, 2))
    costo_servizi = Column(Numeric(14, 2))
    margine_contribuzione = Column(Numeric(14, 2))
    mdc_percentage = Column(Numeric(14, 2))
    costo_personale_accantonamenti = Column(Numeric(14, 2))
    costo_personale = Column(Numeric(14, 2))
    accantonamenti = Column(Numeric(14, 2))

    # Earnings / profitability
    ebipta_1 = Column(Numeric(14, 2))
    ebipta_2 = Column(Numeric(14, 2))
    ebipta_margin = Column(Numeric(14, 2))
    ammortamento = Column(Numeric(14, 2))
    ebit_1 = Column(Numeric(14, 2))
    ebit_2 = Column(Numeric(14, 2))

    spese_generali = Column(Numeric(14, 2))
    spese_generali_percentage = Column(Numeric(14, 2))

    interessi_oneri_1 = Column(Numeric(14, 2))
    interessi_oneri_2 = Column(Numeric(14, 2))
    oneri_finanziari = Column(Numeric(14, 2))

    gestione_straordinaria_fiscale = Column(Numeric(14, 2))
    gestione_straordinaria = Column(Numeric(14, 2))
    imposte = Column(Numeric(14, 2))
    utile_esercizio = Column(Numeric(14, 2))

    totale_attivo = Column(Numeric(14, 2))
    attivo_fisso = Column(Numeric(14, 2))
    attivo_circolante = Column(Numeric(14, 2))
    patrimonio_netto = Column(Numeric(14, 2))
    debito = Column(Numeric(14, 2))

def to_dict(self) -> dict:
    return {
        "id_threshold": self.id_threshold,

        # Averages
        "mol_average": float(self.mol_average) if self.mol_average is not None else None,
        "risultato_operativo_average": float(self.risultato_operativo_average) if self.risultato_operativo_average is not None else None,
        "roe_average": float(self.roe_average) if self.roe_average is not None else None,
        "ros_average": float(self.ros_average) if self.ros_average is not None else None,
        "roi_average": float(self.roi_average) if self.roi_average is not None else None,
        "mol_su_ricavi_average": float(self.mol_su_ricavi_average) if self.mol_su_ricavi_average is not None else None,
        "consumi_su_costi_average": float(self.consumi_su_costi_average) if self.consumi_su_costi_average is not None else None,
        "oneri_su_fatturato_average": float(self.oneri_su_fatturato_average) if self.oneri_su_fatturato_average is not None else None,
        "oneri_su_mol_average": float(self.oneri_su_mol_average) if self.oneri_su_mol_average is not None else None,
        "cash_flow_average": float(self.cash_flow_average) if self.cash_flow_average is not None else None,
        "indice_liquidita_average": float(self.indice_liquidita_average) if self.indice_liquidita_average is not None else None,
        "tasso_intensita_average": float(self.tasso_intensita_average) if self.tasso_intensita_average is not None else None,
        "costi_esterni_su_costi_average": float(self.costi_esterni_su_costi_average) if self.costi_esterni_su_costi_average is not None else None,
        "costi_lavoro_su_costi_average": float(self.costi_lavoro_su_costi_average) if self.costi_lavoro_su_costi_average is not None else None,

        # Min
        "mol_min": float(self.mol_min) if self.mol_min is not None else None,
        "risultato_operativo_min": float(self.risultato_operativo_min) if self.risultato_operativo_min is not None else None,
        "cash_flow_min": float(self.cash_flow_min) if self.cash_flow_min is not None else None,
        "roe_min": float(self.roe_min) if self.roe_min is not None else None,
        "ros_min": float(self.ros_min) if self.ros_min is not None else None,
        "roi_min": float(self.roi_min) if self.roi_min is not None else None,
        "mol_su_ricavi_min": float(self.mol_su_ricavi_min) if self.mol_su_ricavi_min is not None else None,
        "oneri_su_fatturato_min": float(self.oneri_su_fatturato_min) if self.oneri_su_fatturato_min is not None else None,
        "oneri_su_mol_min": float(self.oneri_su_mol_min) if self.oneri_su_mol_min is not None else None,
        "indice_liquidita_min": float(self.indice_liquidita_min) if self.indice_liquidita_min is not None else None,
        "tasso_intensita_min": float(self.tasso_intensita_min) if self.tasso_intensita_min is not None else None,
        "consumi_su_costi_min": float(self.consumi_su_costi_min) if self.consumi_su_costi_min is not None else None,
        "costi_esterni_su_costi_min": float(self.costi_esterni_su_costi_min) if self.costi_esterni_su_costi_min is not None else None,
        "costi_lavoro_su_costi_min": float(self.costi_lavoro_su_costi_min) if self.costi_lavoro_su_costi_min is not None else None,

        # Max
        "mol_max": float(self.mol_max) if self.mol_max is not None else None,
        "risultato_operativo_max": float(self.risultato_operativo_max) if self.risultato_operativo_max is not None else None,
        "cash_flow_max": float(self.cash_flow_max) if self.cash_flow_max is not None else None,
        "roe_max": float(self.roe_max) if self.roe_max is not None else None,
        "ros_max": float(self.ros_max) if self.ros_max is not None else None,
        "roi_max": float(self.roi_max) if self.roi_max is not None else None,
        "mol_su_ricavi_max": float(self.mol_su_ricavi_max) if self.mol_su_ricavi_max is not None else None,
        "oneri_su_fatturato_max": float(self.oneri_su_fatturato_max) if self.oneri_su_fatturato_max is not None else None,
        "oneri_su_mol_max": float(self.oneri_su_mol_max) if self.oneri_su_mol_max is not None else None,
        "indice_liquidita_max": float(self.indice_liquidita_max) if self.indice_liquidita_max is not None else None,
        "tasso_intensita_max": float(self.tasso_intensita_max) if self.tasso_intensita_max is not None else None,
        "consumi_su_costi_max": float(self.consumi_su_costi_max) if self.consumi_su_costi_max is not None else None,
        "costi_esterni_su_costi_max": float(self.costi_esterni_su_costi_max) if self.costi_esterni_su_costi_max is not None else None,
        "costi_lavoro_su_costi_max": float(self.costi_lavoro_su_costi_max) if self.costi_lavoro_su_costi_max is not None else None,

        # Base KPI components
        "ricavi": float(self.ricavi) if self.ricavi is not None else None,
        "costi_totali": float(self.costi_totali) if self.costi_totali is not None else None,
        "costi_esterni": float(self.costi_esterni) if self.costi_esterni is not None else None,
        "consumi_materiale": float(self.consumi_materiale) if self.consumi_materiale is not None else None,
        "costo_servizi": float(self.costo_servizi) if self.costo_servizi is not None else None,
        "margine_contribuzione": float(self.margine_contribuzione) if self.margine_contribuzione is not None else None,
        "mdc_percentage": float(self.mdc_percentage) if self.mdc_percentage is not None else None,
        "costo_personale_accantonamenti": float(self.costo_personale_accantonamenti) if self.costo_personale_accantonamenti is not None else None,
        "costo_personale": float(self.costo_personale) if self.costo_personale is not None else None,
        "accantonamenti": float(self.accantonamenti) if self.accantonamenti is not None else None,

        # Earnings / profitability
        "ebipta_1": float(self.ebipta_1) if self.ebipta_1 is not None else None,
        "ebipta_2": float(self.ebipta_2) if self.ebipta_2 is not None else None,
        "ebipta_margin": float(self.ebipta_margin) if self.ebipta_margin is not None else None,
        "ammortamento": float(self.ammortamento) if self.ammortamento is not None else None,
        "ebit_1": float(self.ebit_1) if self.ebit_1 is not None else None,
        "ebit_2": float(self.ebit_2) if self.ebit_2 is not None else None,

        "spese_generali": float(self.spese_generali) if self.spese_generali is not None else None,
        "spese_generali_percentage": float(self.spese_generali_percentage) if self.spese_generali_percentage is not None else None,

        "interessi_oneri_1": float(self.interessi_oneri_1) if self.interessi_oneri_1 is not None else None,
        "interessi_oneri_2": float(self.interessi_oneri_2) if self.interessi_oneri_2 is not None else None,
        "oneri_finanziari": float(self.oneri_finanziari) if self.oneri_finanziari is not None else None,

        "gestione_straordinaria_fiscale": float(self.gestione_straordinaria_fiscale) if self.gestione_straordinaria_fiscale is not None else None,
        "gestione_straordinaria": float(self.gestione_straordinaria) if self.gestione_straordinaria is not None else None,
        "imposte": float(self.imposte) if self.imposte is not None else None,
        "utile_esercizio": float(self.utile_esercizio) if self.utile_esercizio is not None else None,

        "totale_attivo": float(self.totale_attivo) if self.totale_attivo is not None else None,
        "attivo_fisso": float(self.attivo_fisso) if self.attivo_fisso is not None else None,
        "attivo_circolante": float(self.attivo_circolante) if self.attivo_circolante is not None else None,
        "patrimonio_netto": float(self.patrimonio_netto) if self.patrimonio_netto is not None else None,
        "debito": float(self.debito) if self.debito is not None else None,
    }


