
"""
Localization Utility

This module provides centralized message strings for different languages.
Currently supports English ('en') and Italian ('it').
"""

MESSAGES = {
    "en": {
        # Auth / Token Verification
        "logout_success": "Logout successful",
        "logout_failed": "Logout failed",
        "verify_success": "Token verified successfully",
        "verify_failed": "Token verification failed",
        "verify_unauthorized": "We could not verify your login. Please make sure you are logged in with a valid account and try again.",
        "missing_token": "Please provide the access token to continue.",
        "missing_data": "Request data is required",
        "missing_claims": "Token does not contain required user information",
        "sync_failed": "User synchronization failed",
        "account_inactive": "Your account is inactive. Please contact support to activate your account.",
        "account_suspended": "Your account has been suspended. Please contact support for assistance.",
        "account_blocked": "Your account has been blocked. Please contact support.",
        "account_pending": "Your account is pending approval. Please wait for admin approval.",
        "account_status_error": "Your account status is {status}. Please contact support.",
        "invalid_auth_header": "Authorization header must be in format: Bearer <token>",
        "missing_auth": "Please provide Authorization header or valid session cookie",
        "user_not_found": "User associated with token does not exist",
        "invalid_token": "Invalid or expired token",
        "authorization_required": "Authorization header is required",
        "Authentication failed": "Authentication failed",
        "company_already_exists": "Company already exists",
        "company_found_db": "Company found in database",
        "company_found_creditsafe": "Company found in CreditSafe",
        "company_not_found_search": "Company not found in Database or CreditSafe",
        "vat_required_lookup": "VAT number is required for lookup",
        "company_data_retrieved": "Company data retrieved successfully",
        "lookup_failed": "Lookup failed",
        "lookup_error": "An unexpected error occurred during lookup",
        
        # License Stats
        "license_stats_success": "License statistics retrieved successfully",
        "license_stats_admin_only": "Only admin users can access license statistics",
        "license_stats_failed": "Failed to calculate license statistics",
        "license_stats_error": "Failed to retrieve license statistics",

        # Defaults & Global Errors
        "default_success": "Operation completed successfully",
        "default_error": "An error occurred",
        "validation_failed": "Validation failed",
        "resource_not_found": "Resource not found",
        "method_not_allowed": "The method is not allowed for the requested URL.",
        "internal_server_error": "Internal server error",
        "unexpected_error": "An unexpected error occurred",
        "access_forbidden": "Access forbidden",
        "unauthorized_access": "Unauthorized access",

        # User Management
        "user_list_success": "Users retrieved successfully",
        "user_list_failed": "Failed to retrieve users",
        "user_create_success": "User created successfully",
        "user_create_failed": "Failed to create user",
        "user_update_success": "User updated successfully",
        "user_update_failed": "Failed to update user",
        "user_delete_success": "User deleted successfully",
        "user_delete_failed": "Failed to delete user",
        "user_hard_delete_success": "User permanently deleted successfully",
        "user_hard_delete_failed": "Failed to permanently delete user",
        "user_get_success": "User retrieved successfully",
        "user_get_failed": "Failed to retrieve user",
        "user_password_change_success": "Password changed successfully",
        "user_password_change_failed": "Failed to change password",
        "input_validation_failed": "Input validation failed",
        "temp_user_update_success": "Temp user updated successfully",
        "temp_user_update_failed": "Failed to update temp user",
        "temp_user_delete_success": "Temp user deleted successfully",
        "temp_user_delete_failed": "Failed to delete temp user",
        "temp_user_not_found": "Temp user not found",
        
        # Role/Permission Messages
        "authentication_required": "Authentication required",
        "permission_denied": "Permission denied",
        "staff_create_only": "Staff can only create admin or user roles",
        "admin_create_only": "Admin can only create admin or user roles",
        "user_cannot_create": "User role cannot create other users",
        "unknown_creator_role": "Unknown creator role: {role}",
        "staff_manage_only": "Staff can only manage admin or user",
        "admin_manage_only": "Admin can only manage admin or user",
        "insufficient_permissions": "Insufficient permissions to manage {role}",
        "unknown_permission": "Unknown permission: {action}",
        "permission_required": "Permission denied. Required roles: {roles}",
        
        # OTP Messages
        "otp_sending": "OTP is being sent to your email",
        "otp_check_email": "OTP will arrive shortly. Please check your email.",
        "otp_create_failed": "Failed to create OTP",
        "otp_verified": "OTP verified successfully",
        "otp_invalid": "Invalid OTP",
        "otp_verify_failed": "Failed to verify OTP",
        "otp_invalid_expired": "Invalid or expired OTP. Please request a new one.",
        "otp_cleanup_success": "Cleaned up {count} expired OTPs",
        "otp_cleanup_failed": "Failed to cleanup OTPs",
        
        # Password Reset Messages
        "password_reset_email_sent": "If this email is registered, you will receive a reset link shortly.",
        "password_reset_check_email": "Please check your email for the reset link.",
        "password_reset_request_failed": "Password reset request failed",
        "password_reset_success": "Password reset successfully",
        "password_reset_failed": "Password reset failed",
        "password_reset_invalid_token": "Input validation failed: invalid token",
        "password_reset_cleanup_success": "Cleaned up {count} expired password reset tokens",
        "password_reset_cleanup_failed": "Failed to cleanup tokens",
        
        # Health Check Messages
        "health_system_healthy": "System is healthy",
        "health_check_failed": "System health check failed",
        "health_detailed_success": "Detailed health check completed",
        "health_detailed_failed": "Detailed health check failed",
        "health_summary_success": "Health summary retrieved successfully",
        "health_summary_failed": "Health summary failed",
        
        # Company Messages
        "request_body_required": "Request body is required",
        "validation_error": "Validation error",
        "company_create_failed": "Failed to create company", 
        "company_retrieve_failed": "Failed to retrieve company",
        "company_update_failed": "Failed to update company",
        "company_delete_failed": "Failed to delete company",
        "permission_denied_use_user_endpoint": "Permission denied. Use /user/{id} endpoint to get your companies.",
        "companies_retrieve_failed": "Failed to retrieve companies",
        "permission_denied_own_companies": "Permission denied. {role}s can only access their own companies.",
        "cannot_access_others_companies": "{role} cannot access other users' companies",
        "user_not_found_id": "User with ID {id} not found",
        "user_companies_retrieve_failed": "Failed to retrieve user companies",
        "admin_own_companies_only": "Permission denied. Admins can only access their own companies.",
        "admin_cannot_access_others": "Admin cannot access other admins' companies",
        "user_no_access_company_lists": "Permission denied. Users cannot access company lists.",
        "user_role_no_permission": "User role does not have permission to access company lists",
        "user_not_found": "User not found",

        # Pre-Dashboard Messages
        "pre_dashboard_retrieve_failed": "Failed to retrieve pre-dashboard record",
        "pre_dashboard_update_failed": "Failed to update pre-dashboard record",
        
        # Balance Sheet Messages
        "company_id_required": "Valid company_id is required",
        "file_required": "File is required",
        "year_required": "Year is required",
        "type_required": "Type is required",
        "mode_required": "Mode is required",
        "balance_upload_failed": "Failed to upload balance sheet",
        "balance_retrieve_failed": "Failed to retrieve balance sheet",
        "balances_retrieve_failed": "Failed to retrieve balance sheets",
        "balance_id_required": "Valid id_balance is required",
        "balance_delete_failed": "Failed to delete balance sheet",

        # Benchmark Messages
        "benchmark_create_success": "Benchmark report created successfully",
        "benchmark_create_failed": "Failed to create benchmark",
        "benchmark_create_error": "Failed to create benchmark report",
        "benchmark_list_retrieve_failed": "Failed to retrieve benchmark report list",
        "balance_years_retrieve_failed": "Failed to retrieve balance sheet years",
        "report_id_required": "Report ID is required",
        "benchmarks_fetch_success": "Benchmarks fetched successfully",
        "benchmarks_fetch_failed": "Failed to fetch benchmarks",
        "benchmark_delete_success": "Benchmark report deleted successfully",
        "benchmark_delete_failed": "Failed to delete benchmark report",
        "name_and_note_required": "Both 'name' and 'note' are required",
        "benchmark_note_update_success": "Benchmark report note updated successfully",
        "benchmark_note_update_failed": "Failed to update benchmark report note",
        "competitor_comparison_create_success": "Competitor comparison created successfully",
        "competitor_comparison_create_failed": "Failed to create competitor comparison",
        "competitor_reports_fetch_success": "Competitor reports fetched successfully",
        "competitor_reports_fetch_failed": "Failed to fetch competitor reports",
        # Comparison Report Messages
        "id_balance_year1_required": "id_balance_year1 is required",
        "id_balance_year2_required": "id_balance_year2 is required",
        "id_balance_year1_positive": "id_balance_year1 must be a positive integer",
        "id_balance_year2_positive": "id_balance_year2 must be a positive integer",
        "balance_ids_must_differ": "Both balance sheet IDs must be different",
        "comparison_report_generation_failed": "Failed to generate comparison report",
        "comparison_reports_retrieve_failed": "Failed to retrieve comparison reports",
        # Auth0 Service Messages
        "auth_header_invalid": "Invalid authorization header",
        "auth_token_required": "Authorization token required",
        "auth_token_invalid_expired": "Invalid or expired token",
        "account_not_active": "Account is not active",
        "super_admin_access_required": "Super admin access required",
        "admin_access_required": "Admin access required",
        "auth0_user_creation_failed": "Auth0 user creation failed",
        "auth0_request_failed": "Auth0 request failed",
        "password_reset_error": "Password reset error",
        "auth0_role_assignment_failed": "Auth0 role assignment failed",
        "auth0_management_config_missing": "Missing Auth0 management configuration",
        "auth0_user_authentication_failed": "User authentication failed",
        # Auth User Service Messages
        "current_user_not_found": "Current user not found",
        "creator_user_not_found": "Creator user does not exist",
        "email_already_exists": "Email already exists",
        "user_email_exists": "User with email {email} already exists",
        "user_email_processing": "User with email {email} is already being processed",
        "role_cannot_create_admin": "Role '{role}' cannot create admin users",
        "invalid_license_allocation": "Invalid license allocation",
        "license_allocation_admin_only": "Cannot allocate licenses to role '{role}'. Only admin role can receive licenses.",
        "auth0_user_creation_failed_server": "Failed to create user in Auth0",
        "user_created_success": "User created successfully in Auth0",
        "user_creation_failed": "Failed to create user",
        "user_not_found": "User not found",
        "user_does_not_exist": "User does not exist",
        "users_fetched_success": "Users fetched successfully.",
        "users_list_failed": "Failed to get users list",
        "user_details_success": "User details retrieved successfully",
        "user_details_failed": "Failed to get user details",
        "validation_failed": "Validation failed",
        "license_update_failed": "License update failed",
        "company_mapping_update_failed": "Company mapping update failed",
        "update_failed": "Update failed",
        "user_updated_success": "User updated successfully",
        "self_deletion_not_allowed": "Self-deletion not allowed",
        "cannot_delete_own_account": "You cannot delete your own account",
        "cannot_delete_yourself": "You cannot delete yourself",
        "delete_failed": "Delete failed",
        "user_deleted_success": "User deleted successfully",
        "user_delete_failed": "Failed to delete user",
        "user_permanently_deleted_success": "User permanently deleted successfully",
        "password_change_failed_msg": "Password change failed",
        "password_changed_success": "Password changed successfully",
        "password_change_error": "Failed to change password",
        # Hierarchy Messages
        "hierarchy_user_action_self_only": "Users with role 'user' can only {action} themselves",
        "hierarchy_user_cannot_action": "Users with role 'user' cannot {action} other users",
        "hierarchy_admin_action_created_only": "You can only {action} users you directly created or yourself",
        "hierarchy_role_action_denied": "Role '{user_role}' does not have permission to {action} users",
        "hierarchy_staff_cannot_manage_superadmin": "Staff cannot manage superadmin users",
        "hierarchy_staff_cannot_delete_superadmin": "Staff cannot delete superadmin users",
        "hierarchy_admin_delete_created_only": "You can only delete users you created",
        "hierarchy_user_cannot_delete_others": 'Users with role "user" cannot delete other users',
        # OTP Service Messages
        "account_inactive": "Account inactive",
        "account_not_active_support": "Your account is not active. Please contact support.",
        "email_sending_failed": "Email sending failed",
        "otp_email_send_failed": "Failed to send OTP email. Please try again.",
        "otp_create_failed": "Failed to create OTP",
        "otp_sent_success": "OTP sent successfully",
        "otp_verified_dev_success": "OTP verified successfully (development mode)",
        "invalid_otp": "Invalid OTP",
        "invalid_otp_message": "Invalid or expired OTP. Please request a new one or use 123456 for development.",
        "otp_verified_success": "OTP verified successfully",
        "otp_verify_failed": "Failed to verify OTP",
        # Password Reset Service Messages
        "rate_limit_exceeded": "Rate limit exceeded",
        "rate_limit_exceeded_message": "Too many reset requests for this email. Please wait before trying again.",
        "password_reset_request_success": "If this email is registered, you will receive a reset link.",
        "database_error": "Database error",
        "generic_error_message": "Please try again later",
        "password_reset_request_failed": "Password reset request failed",
        "invalid_reset_token": "Invalid reset token",
        "token_invalid_expired": "The reset link is invalid or has expired",
        "token_expired": "Token expired",
        "token_expired_message": "The reset link has expired. Please request a new one.",
        "token_already_used": "Token already used",
        "token_already_used_message": "This reset link has already been used. Please request a new one.",
        "user_not_found_inactive": "The user account is not found or inactive",
        "token_valid": "Token is valid",
        "token_verification_failed": "Token verification failed",
        "auth0_user_not_found": "Auth0 user not found",
        "user_auth0_config_error": "User account is not properly configured with Auth0",
        "password_reset_failed": "Password reset failed",
        "auth0_reset_failed": "Failed to reset password in Auth0",
        "password_reset_success_login": "Password reset successfully. Please log in with your new password.",
        # License Service Messages
        "error_calculating_stats": "Error calculating stats: {error}",
        "unable_validate_licenses": "Unable to validate licenses: {error}",
        "no_licenses_to_allocate": "You don't have any licenses to allocate",
        "allocate_reserved_limit": "Cannot allocate {requested} licenses. {reason}. You can transfer maximum {max} licenses.",
        "allocate_transfer_limit": "Cannot allocate {requested} licenses. Only {max} licenses available to transfer.",
        "no_licenses_create_company": "No licenses available to create a company. ",
        "no_licenses_owned": "You don't have any licenses.",
        "all_licenses_in_use": "All {count} licenses are in use.",
        "no_licenses_found_user": "No licenses found for user",
        "insufficient_licenses_available": "Only {available} licenses available, but {requested} requested",
        "error_retrieving_licenses": "Error retrieving licenses: {error}",
        "error_transferring_licenses": "Error transferring licenses: {error}",
        "parent_admin_not_found": "Parent admin not found",
        "cannot_decrease_licenses_used": "Cannot decrease licenses by {amount}. User has {total} total licenses, but {used} are used by companies. Only {unused} unused licenses available to remove.",
        "unable_remove_licenses": "Unable to remove {amount} licenses. {error}",
        "role_cannot_update_licenses": 'Role "{role}" cannot update admin licenses',
        "error_updating_licenses": "Error updating licenses: {error}",
        "parent_not_enough_licenses": "Parent admin does not have enough licenses. {error}",
        # Companies Service Messages
        "user_role_cannot_manage_companies": "Users with role 'user' cannot manage companies",
        "only_admin_create_companies": "Only superadmin, staff, and admin can create companies",
        "company_not_found": "Company not found",
        "manage_own_companies_only": "You can only {action} companies you created",
        "parent_company_not_found": "Parent company not found",
        "parent_company_not_found_msg": "Parent company {id} not found",
        "user_required_title": "User required",
        "user_login_required": "User must be logged in to create a company",
        "current_user_not_exist": "Current user does not exist",
        "no_licenses_create_company_msg": "You do not have any available licenses to create a company. All your licenses are currently in use.",
        "company_create_failed": "Failed to create company",
        "company_created_success": "Company created successfully",
        "company_retrieved_success": "Company retrieved successfully",
        "company_retrieve_failed": "Failed to retrieve company",
        "company_updated_success": "Company updated successfully",
        "company_update_failed": "Failed to update company",
        "company_deleted_success": "Company deleted successfully",
        "company_delete_failed": "Failed to delete company",
        "companies_retrieve_failed": "Failed to retrieve companies",
        "companies_retrieved_success": "Companies retrieved successfully",
        "balance_sheets_required_2": "At least 2 active balance sheets required.",
        "no_comparison_found": "No comparison found for this company",
        "incomplete_comparison_data": "Incomplete comparison data",
        "comparison_deleted_balances": "Comparison references deleted balance sheets. Valid comparison not available.",
        "ebitda_values_not_found": "EBITDA values not found in kpi_values table",
        "ebitda_zero_error": "Cannot calculate status: EBITDA2 is zero",
        "status_calculation_error": "Error calculating status: {error}",
        "no_companies_assigned": "No companies assigned to user {user}",
        "user_companies_retrieved_success": "Companies for user {user} retrieved successfully",
        "user_companies_retrieve_failed": "Failed to retrieve user companies",
        "companies_list_retrieved_success": "Companies list retrieved successfully",
        "parent_company_id_required": "Parent company ID is required",
        "competitor_companies_retrieved_success": "Competitor companies for parent company retrieved successfully",
        "competitor_companies_retrieve_failed": "Failed to retrieve competitor companies for parent company {id_company}",
        "region_and_ateco_required": "Both region and ATECO code are required.",
        "invalid_region_or_ateco": "Invalid region or ATECO code. No matching sector found.",
        # Pre-Dashboard Service Messages
        "pre_dashboard_missing": "Pre-dashboard record missing",
        "pre_dashboard_not_created_msg": "Pre-dashboard record was not created during company creation",
        "pre_dashboard_not_found_msg": "Pre-dashboard record not found for this company",
        "pre_dashboard_retrieved_success": "Pre-dashboard retrieved successfully",
        "pre_dashboard_retrieve_failed": "Failed to retrieve pre-dashboard record",
        "pre_dashboard_create_failed": "Failed to create pre-dashboard record",
        "pre_dashboard_update_failed": "Failed to update pre-dashboard record",
        "pre_dashboard_updated_success": "Pre-dashboard updated successfully",
        # Balance Sheet Service Messages
        "invalid_competitor_company_msg": "Invalid competitor company: parent_company_id is missing",
        "competitor_access_denied_msg": "You do not have access to this competitor company. You must be assigned to its parent company (id_company={parent_company_id}).",
        "company_access_denied_msg": "You do not have access to company {company_id}. Only companies assigned to you can be accessed.",
        "unknown_user_role": "Unknown user role: {user_role}",
        "year_mismatch": "Year mismatch. {file_type} reports {pdf_year} while payload contains {payload_year}.",
        "month_mismatch": "Month mismatch. {file_type} reports {pdf_month} while payload contains {payload_month}.",
        "verification_failed_msg": "Failed to verify existing balance sheets",
        "delete_failed_msg": "Failed to delete balance and related benchmark data",
        "delete_existing_failed_msg": "Failed to delete existing balance sheets: {error}",
        "file_required": "File is required",
        "invalid_file_type": "Only PDF, XLSX, and XBRL/XML files are allowed",
        "invalid_mode": "Invalid mode: {mode}. Valid modes are: pdf, xlsx, xbrl, xml, manual",
        "mode_mismatch": 'Mode is set to "{mode_display}" but uploaded file is {file_ext}. Please upload a {mode_display} file or change the mode.',
        "invalid_year": "Invalid year. Must be between 1900 and 2100",
        "invalid_month": "Invalid month. Must be between 1 and 12",
        "unknown_excel_format": "Unknown Excel format",
        "excel_script_error": "Could not determine matching script for this XLSX file",
        "unsupported_file_type": "Unsupported file type: {file_ext}",
        "extraction_error": "Extraction error",
        "extraction_failed_msg": "Failed to extract data from {file_ext}: {error}",
        "balance_sheet_exists": "Balance sheet already exists.",
        "save_balance_failed": "Failed to save balance record",
        "balance_sheet_uploaded_success": "Balance sheet uploaded successfully.",
        "balance_sheet_upload_failed": "Failed to upload balance sheet",
        "valid_company_id_required": "Valid company_id is required",
        "balance_sheets_retrieve_failed": "Failed to retrieve balance sheets",
        "balance_sheets_retrieved_success": "Balance sheets retrieved successfully",
        "valid_balance_id_required": "Valid id_balance is required",
        "balance_sheet_id_not_found": "Balance sheet with ID {id_balance} not found",
        "balance_sheet_retrieved_success": "Balance sheet retrieved successfully",
        "balance_sheet_retrieve_failed": "Failed to retrieve balance sheet",
        "balance_sheet_not_found": "Balance sheet not found",
        "already_deleted": "Already deleted",
        "balance_sheet_already_deleted": "Balance sheet is already deleted",
        "balance_sheet_deleted_success": "Balance sheet deleted successfully",
        "balance_sheet_delete_failed": "Failed to delete balance sheet",
        "balance_does_not_belong": "Balance sheet {id_balance} does not belong to company {company_id}",
        # Comparison Report Service Messages
        "access_denied_permission": "Access denied: You don't have permission to access this company",
        "balance_sheet_no_data": "Balance sheet has no balance data",
        "balance_sheet_id_no_data": "Balance sheet {id_balance} has no balance data",
        "kpi_calc_stored_success": "KPIs calculated and stored successfully",
        "kpi_calc_failed": "Failed to calculate KPIs",
        "insufficient_balance_sheets": "Insufficient balance sheets for comparison.",
        "comparison_report_exists": "Comparison report already exists for the two most recent balance sheets",
        "comparison_report_auto_generated_success": "Comparison report auto-generated successfully",
        "comparison_report_auto_generated_failed": "Failed to auto-generate comparison report",
        "kpi_calc_uploaded_no_comparison": "KPIs calculated for uploaded balance sheet. No comparison generated (not in last 2 years).",
        "comparison_report_generation_error": "Error during auto-generation of comparison report",
        "balance_sheet_same_company_required": "Both balance sheets must belong to the same company",
        "failed_store_kpi_values": "Failed to store KPI values",
        "failed_create_analysis": "Failed to create analysis record",
        "failed_create_report": "Failed to create report record",
        "failed_create_analysis_kpi": "Failed to create analysis KPI for year {year}: {error}",
        "comparison_report_generated_success": "Comparison report generated successfully",
        "comparison_report_generation_failed": "Failed to generate comparison report",
        "comparison_reports_retrieved_success": "Comparison reports retrieved successfully",
        "comparison_reports_retrieve_failed": "Failed to retrieve comparison reports",
        "no_balance_sheets_found": "No balance sheets found for this company",
        "min_balance_sheets_required": "Minimum 2 balance sheets are required for comparison.",
        # KPI Status Services Messages
        # Synthesis
        "insufficient_historical_data": "Insufficient historical data to evaluate performance trends.",
        "synthesis_2_years": "The company recorded a {direction} of {yoy} compared to the previous year.",
        "synthesis_3_years": "The company recorded a {long_dir} of {trend} compared to {y0}. Compared to the previous fiscal year, the value shows a {short_dir} of {yoy}.",
        # Competitor Synthesis
        "competitor_insufficient_data": "Insufficient data for competitor comparison.",
        "competitor_levels_similar": "Both companies are at similar levels. Competitor's {kpi_name} is {comp_val_str} while your company's average is {company_val_str} (across years {years_str}). Performance gap: {gap}% - essentially equal.",
        "competitor_ahead": "Competitor is AHEAD by {ahead_by}%. Competitor's {kpi_name} is {comp_val_str} compared to your company's average of {company_val_str} (across years {years_str}). This means competitor is performing {goal_percentage}% of your company's level. Your company needs to improve by {ahead_by}% to match competitor.",
        "company_ahead": "Your company is AHEAD by {ahead_by}%. Your company's average {kpi_name} is {company_val_str} (across years {years_str}) compared to competitor's {comp_val_str}. Competitor is performing {goal_percentage}% of your company's level. Your company maintains a competitive advantage of {ahead_by}%.",
        # Competitor Advice
        "competitor_advice_closely_matched": " Both companies are closely matched. Focus on maintaining competitive edge and identifying differentiation opportunities.",
        "competitor_advice_significantly_ahead": " Competitor is significantly ahead ({diff}% better). Urgent action required: Analyze competitor strategies, benchmark best practices, and implement improvement initiatives to close the gap.",
        "competitor_advice_advantage": " Competitor has an advantage ({diff}% better). Review operational efficiency, cost structures, and pricing strategies to improve competitive position.",
        "competitor_advice_balanced": " Competitive position is balanced ({goal_percentage}% of competitor level). Continue optimizing operations to strengthen and maintain market position.",
        "competitor_advice_company_ahead": " Your company is ahead ({diff}% better than competitor). Leverage this advantage while addressing any operational weaknesses to maintain competitive leadership.",
        "competitor_advice_strong_advantage": " Your company has a strong competitive advantage ({diff}% better). Maintain this leadership position through continuous improvement and innovation.",
        # KPI Suggestions (EBITDA)
        "kpi_EBITDA_GOOD_suggestion": "Maintain strong operating performance and continue current efficiency initiatives.",
        "kpi_EBITDA_AVERAGE_suggestion": "Review operating costs and improve efficiency to strengthen profitability.",
        "kpi_EBITDA_RISKY_suggestion": "Reduce operating expenses and reassess pricing strategies urgently.",
        "kpi_EBITDA_ALARMING_suggestion": "Immediate restructuring is required to restore operating profitability.",
        # KPI Suggestions (EBIT_Reddito_Operativo)
        "kpi_EBIT_Reddito_Operativo_GOOD_suggestion": "Operating income is healthy; sustain current business operations.",
        "kpi_EBIT_Reddito_Operativo_AVERAGE_suggestion": "Improve operational efficiency and monitor cost structures.",
        "kpi_EBIT_Reddito_Operativo_RISKY_suggestion": "Operating margins are under pressure; corrective actions are required.",
        "kpi_EBIT_Reddito_Operativo_ALARMING_suggestion": "Critical operational losses detected; immediate intervention needed.",
        # KPI Suggestions (MOL_RICAVI_%)
        "kpi_MOL_RICAVI_%_GOOD_suggestion": "Value creation from revenues is strong; maintain pricing discipline.",
        "kpi_MOL_RICAVI_%_AVERAGE_suggestion": "Analyze cost drivers to improve contribution from revenues.",
        "kpi_MOL_RICAVI_%_RISKY_suggestion": "Low margin on revenues; optimize production and procurement costs.",
        "kpi_MOL_RICAVI_%_ALARMING_suggestion": "Severe margin erosion; urgent review of business model required.",
        # KPI Suggestions (EBITDA_Margin_%)
        "kpi_EBITDA_Margin_%_GOOD_suggestion": "Profitability margin is strong; continue operational discipline.",
        "kpi_EBITDA_Margin_%_AVERAGE_suggestion": "Improve cost control to enhance EBITDA margins.",
        "kpi_EBITDA_Margin_%_RISKY_suggestion": "Margin decline detected; reassess cost and pricing strategies.",
        "kpi_EBITDA_Margin_%_ALARMING_suggestion": "Critically low margins; immediate corrective measures required.",
        # KPI Suggestions (Margine_Contribuzione_%)
        "kpi_Margine_Contribuzione_%_GOOD_suggestion": "Contribution margin is healthy; current pricing strategy is effective.",
        "kpi_Margine_Contribuzione_%_AVERAGE_suggestion": "Monitor variable costs and adjust pricing if necessary.",
        "kpi_Margine_Contribuzione_%_RISKY_suggestion": "Low contribution margin; cost optimization is required.",
        "kpi_Margine_Contribuzione_%_ALARMING_suggestion": "Contribution margin is unsustainable; urgent action needed.",
        # KPI Suggestions (Patrimonio_Netto)
        "kpi_Patrimonio_Netto_GOOD_suggestion": "Equity position is strong; maintain financial stability.",
        "kpi_Patrimonio_Netto_AVERAGE_suggestion": "Monitor liabilities and gradually strengthen equity.",
        "kpi_Patrimonio_Netto_RISKY_suggestion": "High leverage detected; consider capital reinforcement.",
        "kpi_Patrimonio_Netto_ALARMING_suggestion": "Negative equity signals solvency risk; urgent recapitalization required.",
        # KPI Suggestions (Mark_Up)
        "kpi_Mark_Up_GOOD_suggestion": "Markup levels are healthy; pricing strategy is effective.",
        "kpi_Mark_Up_AVERAGE_suggestion": "Review pricing to improve profitability margins.",
        "kpi_Mark_Up_RISKY_suggestion": "Low markup detected; reassess cost structure and pricing.",
        "kpi_Mark_Up_ALARMING_suggestion": "Markup is insufficient to sustain operations; immediate action required.",
        # KPI Suggestions (Fatturato_Equilibrio_BEP)
        "kpi_Fatturato_Equilibrio_BEP_GOOD_suggestion": "Break-even point is manageable; business sustainability is strong.",
        "kpi_Fatturato_Equilibrio_BEP_AVERAGE_suggestion": "Monitor sales volume to stay above break-even level.",
        "kpi_Fatturato_Equilibrio_BEP_RISKY_suggestion": "Break-even point is high; improve cost efficiency or increase revenues.",
        "kpi_Fatturato_Equilibrio_BEP_ALARMING_suggestion": "Break-even sales are unsustainable; urgent restructuring required.",
        # KPI Suggestions (Spese_Generali_Ratio)
        "kpi_Spese_Generali_Ratio_GOOD_suggestion": "General expenses are well controlled relative to revenues.",
        "kpi_Spese_Generali_Ratio_AVERAGE_suggestion": "Monitor overhead costs to avoid margin pressure.",
        "kpi_Spese_Generali_Ratio_RISKY_suggestion": "High overhead ratio detected; reduce general expenses.",
        "kpi_Spese_Generali_Ratio_ALARMING_suggestion": "Overhead costs are excessive; immediate cost-cutting required.",
        # KPI Suggestions (Ricavi_Totali)
        "kpi_Ricavi_Totali_GOOD_suggestion": "Revenue growth is healthy; continue expansion strategies.",
        "kpi_Ricavi_Totali_AVERAGE_suggestion": "Stabilize revenues and explore growth opportunities.",
        "kpi_Ricavi_Totali_RISKY_suggestion": "Revenue decline detected; strengthen sales and marketing efforts.",
        "kpi_Ricavi_Totali_ALARMING_suggestion": "Severe revenue contraction; immediate business intervention required.",
        # KPI Suggestions (Costi_Variabili)
        "kpi_Costi_Variabili_GOOD_suggestion": "Variable costs are well managed relative to output.",
        "kpi_Costi_Variabili_AVERAGE_suggestion": "Monitor variable cost trends and supplier efficiency.",
        "kpi_Costi_Variabili_RISKY_suggestion": "Variable costs are increasing; optimize procurement and operations.",
        "kpi_Costi_Variabili_ALARMING_suggestion": "Uncontrolled variable costs detected; urgent corrective action required.",
        # Health Service
        "db_connection_healthy_with_count": "Database connection healthy (tables: {count})",
        "db_connection_healthy": "Database connection healthy",
        "db_connection_failed": "Database connection failed: {error}",
        "app_running_with_users": "Application running with {count} users",
        "app_health_check_failed": "Application health check failed: {error}",
        "email_service_configured": "Email service configured",
        "email_service_not_configured": "Email service not configured",
        "email_service_check_failed": "Email service check failed: {error}",
        "ai_services_configured": "AI services configured",
        "ai_services_not_configured": "AI services not configured",
        "ai_services_check_failed": "AI services check failed: {error}",
        "secret_key_not_configured": "SECRET_KEY not properly configured",
        "jwt_secret_key_not_configured": "JWT_SECRET_KEY not properly configured",
        "db_url_not_configured": "DATABASE_URL_DB not configured",
        "external_service_check_failed": "External service health check failed: {error}",
        "performance_metrics_failed": "Performance metrics collection failed: {error}",
        "health_check_failed": "Health check failed: {error}",
        # Benchmark Service
        "company_id_and_balance_required": "company_id and at least one balance sheet are required",
        "balance_sheet_spec_error": "Each balance sheet must have 'year' and 'budgetType' (month is optional)",
        "invalid_budget_type": "Invalid budgetType '{type}'",
        "no_balance_found_with_month": "No balance found for year {year}, budgetType '{type}', month {month}",
        "no_balance_found": "No balance found for year {year}, budgetType '{type}'",
        "benchmark_report_already_exists": "Benchmark report already exists with the same balance sheets",
        "no_kpi_values_found": "No KPI values found for selected balances",
        "benchmark_report_created": "Benchmark report created successfully",
        "report_not_found": "Report not found",
        "analysis_not_found_for_report": "Analysis not found for the report",
        "no_benchmarks_found_for_report": "No benchmarks found for the report",
        "benchmarks_fetched_successfully": "Benchmarks fetched successfully",
        "valid_company_id_required": "Valid company_id is required",
        "no_balance_sheets_found": "No balance sheets found",
        "balance_sheet_years_retrieved": "Balance sheet years retrieved successfully",
        "failed_retrieve_balance_years": "Failed to retrieve balance sheet years",
        "analysis_id_and_kpi_required": "id_analysis and KPI name are required",
        "analysis_not_found": "Analysis not found",
        "no_benchmarks_found_for_analysis": "No benchmarks found for analysis",
        "no_kpi_info_found_for_analysis": "No KPI info found for analysis",
        "kpi_not_found_in_analysis": "KPI '{name}' not found in analysis",
        "benchmark_kpi_note_updated": "Benchmark KPI note updated successfully",
        "no_benchmark_reports_found": "No benchmark reports found",
        "benchmark_reports_retrieved": "Benchmark reports retrieved successfully",
        "report_id_required": "report_id is required",
        "no_analysis_kpi_infos_found": "No analysis kpi infos found for the report",
        "benchmark_deleted_with_competitors": "Benchmark report and {count} competitor report(s) deleted successfully",
        "benchmark_deleted_successfully": "Benchmark report deleted successfully",
        "parent_report_id_required": "parent_report_id is required",
        "competitor_id_required": "competitor_id is required",
        "year_required": "year is required",
        "balancesheet_name_required": "balancesheet_name is required",
        "parent_benchmark_not_found": "Parent benchmark report not found",
        "parent_analysis_not_found": "Parent analysis not found",
        "no_balances_found_in_parent": "No balances found in parent benchmark",
        "main_company_balance_not_found": "Main company balance not found",
        "invalid_competitor_for_company": "Invalid competitor for this company",
        "competitor_balance_not_found": "Competitor balance not found",
        "competitor_benchmark_already_exists": "This Competitor Benchmark Report already exists",
        "competitor_benchmark_created": "Competitor comparison report created successfully",
        "competitor_benchmarks_fetched": "Competitor Benchmark Reports fetched successfully",
        "competitor_companies_retrieved_success": "Competitor companies retrieved successfully",
        "competitor_companies_retrieved_failed": "Failed to retrieve competitor companies",
        "failed_retrieve_competitors": "Failed to retrieve suggested competitors",
        "competitor_already_added_to_benchmark": "This competitor balance sheet has already been added to this benchmark report",
        # Predictive Monitoring & Suggestions
        "pred_sug_ricavi_cause": "Analyze the causes of the reduction to understand if it is a temporary or structural problem.",
        "pred_sug_ricavi_pricing": "Review the pricing strategy: Consider differentiated prices for premium clients or express services.",
        "pred_sug_ricavi_costi_diretti": "Profitability relative to direct costs is low, it may be necessary to review prices or reduce operating costs.",
        "pred_sug_ricavi_mercati": "Expand into new markets: If you work on residential renovations, you could evaluate the commercial or industrial sector.",
        "pred_sug_ricavi_fidelizzazione": "Retain existing customers: Offer incentives, discounts for regular customers and loyalty programs.",
        "pred_sug_ricavi_incasso": "Review the average collection time.",
        "pred_sug_roi_efficiency": "Analyze capital allocation efficiency to improve return on investment.",
        "pred_sug_roi_turnover": "Improve asset turnover by optimizing stock management and collection times.",
        "pred_sug_roe_leverage": "Reassess the capital structure to optimize the balance between debt and equity.",
        "pred_sug_roe_profitability": "Focus on net margin improvement through cost optimization.",
        "pred_sug_ros_margins": "Monitor manufacturing and service costs to improve margins on sales.",
        "pred_sug_ros_mix": "Analyze the product/service mix to push higher-margin offerings.",
        "pred_sug_ebitda_opex": "Reduce fixed operating costs and renegotiate with suppliers.",
        "pred_sug_ebitda_productivity": "Increase staff productivity and optimize internal processes.",
        "pred_sug_mdc_variable": "Strictly control variable costs and production waste.",
        "pred_sug_mdc_volume": "Increase sales volumes to better absorb fixed costs.",
        # New & Granular Suggestions (EN)
        "pred_sug_ricavi_cross_selling": "Implement cross-selling and up-selling strategies on existing customers.",
        "pred_sug_ricavi_digital_marketing": "Invest in targeted digital marketing campaigns to increase visibility.",
        "pred_sug_ricavi_partnership": "Evaluate strategic partnerships to access new customer segments.",
        "pred_sug_roi_low_performing": "Identify and divest low-profitability assets or business units.",
        "pred_sug_roi_reinvestment": "Evaluate reinvestment of profits into high operational efficiency technologies.",
        "pred_sug_roi_working_capital": "Downsize working capital to free up financial resources.",
        "pred_sug_roe_refinancing": "Renegotiate existing debt to reduce financial charges and improve net profit.",
        "pred_sug_roe_equity_structure": "Optimize the mix between equity and debt to maximize return for shareholders.",
        "pred_sug_roe_dividend_policy": "Review dividend policy to balance self-financing and return.",
        "pred_sug_ros_premium_price": "Aim for premium positioning to justify higher margins.",
        "pred_sug_ros_cost_control": "Implement analytical monitoring of direct costs for each product line.",
        "pred_sug_ros_discount_policy": "Review discount policy to prevent excessive margin erosion.",
        "pred_sug_ebitda_energy": "Invest in energy efficiency to reduce fixed overhead costs.",
        "pred_sug_ebitda_outsourcing": "Evaluate outsourcing non-core activities to make costs more flexible.",
        "pred_sug_ebitda_digitalization": "Digitalize administrative processes to reduce management costs.",
        "pred_sug_mdc_supplier_nego": "Renegotiate purchase terms with key raw material suppliers.",
        "pred_sug_mdc_waste_reduction": "Implement lean production protocols to reduce waste and scrap.",
        "pred_sug_mdc_logistics": "Optimize logistics and transport to reduce the impact of variable costs.",
        "pred_sug_gen_consolidation": "Continue quarterly monitoring to consolidate achievements.",
        "pred_sug_gen_scalability": "Evaluate more scalable business models to support future growth.",
        "pred_sug_gen_innovation": "Invest in R&D to maintain competitive advantage.",
        "pred_no_complete_balances": "No complete (final) annual balance sheets found to use as a base for prediction.",
        "pred_no_historical_trend": "Could not identify historical trend from complete balances.",
        "pred_prediction_success": "Prediction generated successfully",
    },
    "it": {
        # Auth / Token Verification
        "logout_success": "Logout effettuato con successo",
        "logout_failed": "Logout fallito",
        "verify_success": "Token verificato con successo",
        "verify_failed": "Verifica del token fallita",
        "verify_unauthorized": "Non siamo riusciti a verificare il tuo login. Assicurati di aver effettuato l'accesso con un account valido e riprova.",
        "missing_token": "Si prega di fornire il token di accesso per continuare.",
        "missing_data": "Dati della richiesta richiesti",
        "missing_claims": "Il token non contiene le informazioni utente richieste",
        "sync_failed": "Sincronizzazione utente fallita",
        "account_inactive": "Il tuo account è inattivo. Contatta il supporto per attivare il tuo account.",
        "account_suspended": "Il tuo account è stato sospeso. Contatta il supporto per assistenza.",
        "account_blocked": "Il tuo account è stato bloccato. Contatta il supporto.",
        "account_pending": "Il tuo account è in attesa di approvazione. Attendi l'approvazione dell'amministratore.",
        "account_status_error": "Lo stato del tuo account è {status}. Contatta il supporto.",
        "invalid_auth_header": "L'intestazione di autorizzazione deve essere nel formato: Bearer <token>",
        "missing_auth": "Si prega di fornire l'intestazione di autorizzazione o un cookie di sessione valido",
        "user_not_found": "L'utente associato al token non esiste",
        "invalid_token": "Token non valido o scaduto",
        "authorization_required": "L'intestazione di autorizzazione è richiesta",
        "Authentication failed": "Autenticazione fallita",
        # License Stats
        "license_stats_success": "Statistiche delle licenze recuperate con successo",
        "license_stats_admin_only": "Solo gli amministratori possono accedere alle statistiche delle licenze",
        "license_stats_failed": "Impossibile calcolare le statistiche delle licenze",
        "license_stats_error": "Impossibile recuperare le statistiche delle licenze",
        # Defaults & Global Errors
        "default_success": "Operazione completata con successo",
        "default_error": "Si è verificato un errore",
        "validation_failed": "Validazione fallita",
        "resource_not_found": "Risorsa non trovata",
        "method_not_allowed": "Il metodo non è consentito per l'URL richiesto.",
        "internal_server_error": "Errore interno del server",
        "unexpected_error": "Si è verificato un errore imprevisto",
        "access_forbidden": "Accesso vietato",
        "unauthorized_access": "Accesso non autorizzato",
        # User Management
        "user_list_success": "Utenti recuperati con successo",
        "user_list_failed": "Impossibile recuperare gli utenti",
        "user_create_success": "Utente creato con successo",
        "user_create_failed": "Impossibile creare l'utente",
        "user_update_success": "Utente aggiornato con successo",
        "user_update_failed": "Impossibile aggiornare l'utente",
        "user_delete_success": "Utente eliminato con successo",
        "user_delete_failed": "Impossibile eliminare l'utente",
        "user_hard_delete_success": "Utente eliminato definitivamente con successo",
        "user_hard_delete_failed": "Impossibile eliminare l'utente definitivamente",
        "user_get_success": "Utente recuperato con successo",
        "user_get_failed": "Impossibile recuperare l'utente",
        "user_password_change_success": "Password cambiata con successo",
        "user_password_change_failed": "Impossibile cambiare la password",
        "input_validation_failed": "Validazione dell'input fallita",
        "temp_user_update_success": "Utente temporaneo aggiornato con successo",
        "temp_user_update_failed": "Impossibile aggiornare l'utente temporaneo",
        "temp_user_delete_success": "Utente temporaneo eliminato con successo",
        "temp_user_delete_failed": "Impossibile eliminare l'utente temporaneo",
        "temp_user_not_found": "Utente temporaneo non trovato",
        # Role/Permission Messages
        "authentication_required": "Autenticazione richiesta",
        "permission_denied": "Permesso negato",
        "staff_create_only": "Lo staff può creare solo ruoli admin o user",
        "admin_create_only": "L'admin può creare solo ruoli admin o user",
        "user_cannot_create": "Il ruolo utente non può creare altri utenti",
        "unknown_creator_role": "Ruolo creatore sconosciuto: {role}",
        "staff_manage_only": "Lo staff può gestire solo admin o user",
        "admin_manage_only": "L'admin può gestire solo admin o user",
        "insufficient_permissions": "Permessi insufficienti per gestire {role}",
        "unknown_permission": "Permesso sconosciuto: {action}",
        "permission_required": "Permesso negato. Ruoli richiesti: {roles}",
        # OTP Messages
        "otp_sending": "L'OTP viene inviato alla tua email",
        "otp_check_email": "L'OTP arriverà a breve. Controlla la tua email.",
        "otp_create_failed": "Impossibile creare OTP",
        "otp_verified": "OTP verificato con successo",
        "otp_invalid": "OTP non valido",
        "otp_verify_failed": "Impossibile verificare OTP",
        "otp_invalid_expired": "OTP non valido o scaduto. Richiedine uno nuovo.",
        "otp_cleanup_success": "Puliti {count} OTP scaduti",
        "otp_cleanup_failed": "Impossibile pulire gli OTP",
        # Password Reset Messages
        "password_reset_email_sent": "Se questa email è registrata, riceverai un link di reimpostazione a breve.",
        "password_reset_check_email": "Controlla la tua email per il link di reimpostazione.",
        "password_reset_request_failed": "Richiesta di reimpostazione password fallita",
        "password_reset_success": "Password reimpostata con successo",
        "password_reset_failed": "Reimpostazione password fallita",
        "password_reset_invalid_token": "Validazione input fallita: token non valido",
        "password_reset_cleanup_success": "Puliti {count} token di reimpostazione password scaduti",
        "password_reset_cleanup_failed": "Impossibile pulire i token",
        # Health Check Messages
        "health_system_healthy": "Il sistema è sano",
        "health_check_failed": "Controllo stato del sistema fallito",
        "health_detailed_success": "Controllo stato dettagliato completato",
        "health_detailed_failed": "Controllo stato dettagliato fallito",
        "health_summary_success": "Riepilogo stato recuperato con successo",
        "health_summary_failed": "Riepilogo stato fallito",
        # Company Messages
        "request_body_required": "Il corpo della richiesta è obbligatorio",
        "validation_error": "Errore di validazione",
        "company_create_failed": "Impossibile creare l'azienda",
        "company_retrieve_failed": "Impossibile recuperare l'azienda",
        "company_update_failed": "Impossibile aggiornare l'azienda",
        "company_delete_failed": "Impossibile eliminare l'azienda",
        "permission_denied_use_user_endpoint": "Permesso negato. Usa l'endpoint /user/{id} per ottenere le tue aziende.",
        "companies_retrieve_failed": "Impossibile recuperare le aziende",
        "permission_denied_own_companies": "Permesso negato. {role} possono accedere solo alle proprie aziende.",
        "cannot_access_others_companies": "{role} non può accedere alle aziende di altri utenti",
        "user_not_found_id": "Utente con ID {id} non trovato",
        "user_companies_retrieve_failed": "Impossibile recuperare le aziende dell'utente",
        "admin_own_companies_only": "Permesso negato. Gli amministratori possono accedere solo alle proprie aziende.",
        "admin_cannot_access_others": "L'amministratore non può accedere alle aziende di altri amministratori",
        "user_no_access_company_lists": "Permesso negato. Gli utenti non possono accedere agli elenchi delle aziende.",
        "user_role_no_permission": "Il ruolo utente non ha il permesso di accedere agli elenchi delle aziende",
        "company_already_exists": "Azienda già esistente",
        "company_found_db": "Azienda trovata nel database",
        "company_found_creditsafe": "Azienda trovata in CreditSafe",
        "company_not_found_search": "Azienda non trovata nel database o in CreditSafe",
        "vat_required_lookup": "Partita IVA obbligatoria per la ricerca",
        "company_data_retrieved": "Dati azienda recuperati con successo",
        "lookup_failed": "Ricerca fallita",
        "lookup_error": "Si è verificato un errore imprevisto durante la ricerca",
        "region_and_ateco_required": "Sia la regione che il codice ATECO sono obbligatori.",
        "invalid_region_or_ateco": "Regione o codice ATECO non validi. Nessun settore corrispondente trovato.",
        # Pre-Dashboard Messages
        "pre_dashboard_retrieve_failed": "Impossibile recuperare il record pre-dashboard",
        "pre_dashboard_update_failed": "Impossibile aggiornare il record pre-dashboard",
        # Balance Sheet Messages
        "company_id_required": "ID azienda valido richiesto",
        "file_required": "File obbligatorio",
        "year_required": "Anno obbligatorio",
        "type_required": "Tipo obbligatorio",
        "mode_required": "Modalità obbligatoria",
        "balance_upload_failed": "Impossibile caricare il bilancio",
        "balance_retrieve_failed": "Impossibile recuperare il bilancio",
        "balances_retrieve_failed": "Impossibile recuperare i bilanci",
        "balance_id_required": "ID bilancio valido richiesto",
        "balance_delete_failed": "Impossibile eliminare il bilancio",
        # Benchmark Messages
        "benchmark_create_success": "Rapporto benchmark creato con successo",
        "benchmark_create_failed": "Impossibile creare il benchmark",
        "benchmark_create_error": "Impossibile creare il rapporto benchmark",
        "benchmark_list_retrieve_failed": "Impossibile recuperare l'elenco dei rapporti benchmark",
        "balance_years_retrieve_failed": "Impossibile recuperare gli anni di bilancio",
        "report_id_required": "ID rapporto richiesto",
        "benchmarks_fetch_success": "Benchmark recuperati con successo",
        "benchmarks_fetch_failed": "Impossibile recuperare i benchmark",
        "benchmark_delete_success": "Rapporto benchmark eliminato con successo",
        "benchmark_delete_failed": "Impossibile eliminare il rapporto benchmark",
        "name_and_note_required": "Sia 'name' che 'note' sono richiesti",
        "benchmark_note_update_success": "Nota del rapporto benchmark aggiornata con successo",
        "benchmark_note_update_failed": "Impossibile aggiornare la nota del rapporto benchmark",
        "competitor_comparison_create_success": "Confronto competitor creato con successo",
        "competitor_comparison_create_failed": "Impossibile creare il confronto competitor",
        "competitor_reports_fetch_success": "Rapporti competitor recuperati con successo",
        "competitor_reports_fetch_failed": "Impossibile recuperare i rapporti competitor",
        # Comparison Report Messages
        "id_balance_year1_required": "id_balance_year1 è obbligatorio",
        "id_balance_year2_required": "id_balance_year2 è obbligatorio",
        "id_balance_year1_positive": "id_balance_year1 deve essere un intero positivo",
        "id_balance_year2_positive": "id_balance_year2 deve essere un intero positivo",
        "balance_ids_must_differ": "Entrambi gli ID di bilancio devono essere diversi",
        "comparison_report_generation_failed": "Impossibile generare il rapporto di confronto",
        "comparison_reports_retrieve_failed": "Impossibile recuperare i rapporti di confronto",
        # Auth0 Service Messages
        "auth_header_invalid": "Intestazione di autorizzazione non valida",
        "auth_token_required": "Token di autorizzazione richiesto",
        "auth_token_invalid_expired": "Token non valido o scaduto",
        "account_not_active": "L'account non è attivo",
        "super_admin_access_required": "Accesso super admin richiesto",
        "admin_access_required": "Accesso admin richiesto",
        "auth0_user_creation_failed": "Creazione utente Auth0 fallita",
        "auth0_request_failed": "Richiesta Auth0 fallita",
        "password_reset_error": "Errore durante il reset della password",
        "auth0_role_assignment_failed": "Assegnazione ruolo Auth0 fallita",
        "auth0_management_config_missing": "Configurazione di gestione Auth0 mancante",
        "auth0_user_authentication_failed": "Autenticazione utente fallita",
        # Auth User Service Messages
        "current_user_not_found": "Utente corrente non trovato",
        "creator_user_not_found": "L'utente creatore non esiste",
        "email_already_exists": "L'email esiste già",
        "user_email_exists": "L'utente con email {email} esiste già",
        "user_email_processing": "L'utente con email {email} è già in elaborazione",
        "role_cannot_create_admin": "Il ruolo '{role}' non può creare utenti amministratori",
        "invalid_license_allocation": "Assegnazione licenze non valida",
        "license_allocation_admin_only": "Impossibile assegnare licenze al ruolo '{role}'. Solo il ruolo admin può ricevere licenze.",
        "auth0_user_creation_failed_server": "Impossibile creare l'utente su Auth0",
        "user_created_success": "Utente creato con successo su Auth0",
        "user_creation_failed": "Impossibile creare l'utente",
        "user_not_found": "Utente non trovato",
        "user_does_not_exist": "L'utente non esiste",
        "users_fetched_success": "Utenti recuperati con successo.",
        "users_list_failed": "Impossibile recuperare l'elenco utenti",
        "user_details_success": "Dettagli utente recuperati con successo",
        "user_details_failed": "Impossibile recuperare i dettagli utente",
        "validation_failed": "Convalida fallita",
        "license_update_failed": "Aggiornamento licenze fallito",
        "company_mapping_update_failed": "Aggiornamento mappatura azienda fallito",
        "update_failed": "Aggiornamento fallito",
        "user_updated_success": "Utente aggiornato con successo",
        "self_deletion_not_allowed": "Auto-eliminazione non consentita",
        "cannot_delete_own_account": "Non puoi eliminare il tuo account",
        "cannot_delete_yourself": "Non puoi eliminare te stesso",
        "delete_failed": "Eliminazione fallita",
        "user_deleted_success": "Utente eliminato con successo",
        "user_delete_failed": "Impossibile eliminare l'utente",
        "user_permanently_deleted_success": "Utente eliminato definitivamente con successo",
        "password_change_failed_msg": "Cambio password fallito",
        "password_changed_success": "Password cambiata con successo",
        "password_change_error": "Impossibile cambiare la password",
        # Hierarchy Messages
        "hierarchy_user_action_self_only": "Gli utenti con ruolo 'user' possono solo {action} se stessi",
        "hierarchy_user_cannot_action": "Gli utenti con ruolo 'user' non possono {action} altri utenti",
        "hierarchy_admin_action_created_only": "Puoi solo {action} utenti che hai creato direttamente o te stesso",
        "hierarchy_role_action_denied": "Il ruolo '{user_role}' non ha permesso di {action} utenti",
        "hierarchy_staff_cannot_manage_superadmin": "Lo staff non può gestire gli utenti superadmin",
        "hierarchy_staff_cannot_delete_superadmin": "Lo staff non può eliminare gli utenti superadmin",
        "hierarchy_admin_delete_created_only": "Puoi eliminare solo utenti che hai creato",
        "hierarchy_user_cannot_delete_others": 'Gli utenti con ruolo "user" non possono eliminare altri utenti',
        # OTP Service Messages
        "account_inactive": "Account inattivo",
        "account_not_active_support": "Il tuo account non è attivo. Contatta il supporto.",
        "email_sending_failed": "Invio email fallito",
        "otp_email_send_failed": "Impossibile inviare l'email OTP. Riprova.",
        "otp_create_failed": "Creazione OTP fallita",
        "otp_sent_success": "OTP inviato con successo",
        "otp_verified_dev_success": "OTP verificato con successo (modalità sviluppo)",
        "invalid_otp": "OTP non valido",
        "invalid_otp_message": "OTP non valido o scaduto. Richiedine uno nuovo o usa 123456 per lo sviluppo.",
        "otp_verified_success": "OTP verificato con successo",
        "otp_verify_failed": "Verifica OTP fallita",
        # Password Reset Service Messages
        "rate_limit_exceeded": "Limite di tentativi superato",
        "rate_limit_exceeded_message": "Troppe richieste di reset per questa email. Attendi prima di riprovare.",
        "password_reset_request_success": "Se questa email è registrata, riceverai un link per reimpostare la password.",
        "database_error": "Errore del database",
        "generic_error_message": "Riprova più tardi",
        "password_reset_request_failed": "Richiesta di reset password fallita",
        "invalid_reset_token": "Token di reset non valido",
        "token_invalid_expired": "Il link di reset non è valido o è scaduto",
        "token_expired": "Token scaduto",
        "token_expired_message": "Il link di reset è scaduto. Richiedine uno nuovo.",
        "token_already_used": "Token già usato",
        "token_already_used_message": "Questo link di reset è già stato usato. Richiedine uno nuovo.",
        "user_not_found_inactive": "L'account utente non è stato trovato o non è attivo",
        "token_valid": "Token valido",
        "token_verification_failed": "Verifica del token fallita",
        "auth0_user_not_found": "Utente Auth0 non trovato",
        "user_auth0_config_error": "L'account utente non è configurato correttamente con Auth0",
        "password_reset_failed": "Reset password fallito",
        "auth0_reset_failed": "Impossibile reimpostare la password su Auth0",
        "password_reset_success_login": "Password reimpostata con successo. Accedi con la nuova password.",
        # License Service Messages
        "error_calculating_stats": "Errore nel calcolo delle statistiche: {error}",
        "unable_validate_licenses": "Impossibile convalidare le licenze: {error}",
        "no_licenses_to_allocate": "Non hai licenze da assegnare",
        "allocate_reserved_limit": "Impossibile assegnare {requested} licenze. {reason}. Puoi trasferire al massimo {max} licenze.",
        "allocate_transfer_limit": "Impossibile assegnare {requested} licenze. Solo {max} licenze disponibili per il trasferimento.",
        "no_licenses_create_company": "Nessuna licenza disponibile per creare un'azienda. ",
        "no_licenses_owned": "Non hai alcuna licenza.",
        "all_licenses_in_use": "Tutte le {count} licenze sono in uso.",
        "no_licenses_found_user": "Nessuna licenza trovata per l'utente",
        "insufficient_licenses_available": "Solo {available} licenze disponibili, ma ne sono state richieste {requested}",
        "error_retrieving_licenses": "Errore nel recupero delle licenze: {error}",
        "error_transferring_licenses": "Errore nel trasferimento delle licenze: {error}",
        "parent_admin_not_found": "Amministratore genitore non trovato",
        "cannot_decrease_licenses_used": "Impossibile ridurre le licenze di {amount}. L'utente ha {total} licenze totali, ma {used} sono usate dalle aziende. Solo {unused} licenze inutilizzate disponibili per la rimozione.",
        "unable_remove_licenses": "Impossibile rimuovere {amount} licenze. {error}",
        "role_cannot_update_licenses": 'Il ruolo "{role}" non può aggiornare le licenze admin',
        "error_updating_licenses": "Errore nell'aggiornamento delle licenze: {error}",
        "parent_not_enough_licenses": "L'amministratore genitore non ha abbastanza licenze. {error}",
        # Companies Service Messages
        "user_role_cannot_manage_companies": "Gli utenti con ruolo 'user' non possono gestire le aziende",
        "only_admin_create_companies": "Solo superadmin, staff e admin possono creare aziende",
        "company_not_found": "Azienda non trovata",
        "manage_own_companies_only": "Puoi {action} solo le aziende che hai creato",
        "parent_company_not_found": "Azienda madre non trovata",
        "parent_company_not_found_msg": "Azienda madre {id} non trovata",
        "user_required_title": "Utente richiesto",
        "user_login_required": "L'utente deve aver effettuato l'accesso per creare un'azienda",
        "current_user_not_exist": "L'utente corrente non esiste",
        "no_licenses_create_company_msg": "Non hai licenze disponibili per creare un'azienda. Tutte le tue licenze sono attualmente in uso.",
        "company_create_failed": "Creazione azienda fallita",
        "company_created_success": "Azienda creata con successo",
        "company_retrieved_success": "Azienda recuperata con successo",
        "company_retrieve_failed": "Recupero azienda fallito",
        "company_updated_success": "Azienda aggiornata con successo",
        "company_update_failed": "Aggiornamento azienda fallito",
        "company_deleted_success": "Azienda eliminata con successo",
        "company_delete_failed": "Eliminazione azienda fallita",
        "companies_retrieve_failed": "Recupero aziende fallito",
        "companies_retrieved_success": "Aziende recuperate con successo",
        "balance_sheets_required_2": "Sono richiesti almeno 2 bilanci attivi.",
        "no_comparison_found": "Nessun confronto trovato per questa azienda",
        "incomplete_comparison_data": "Dati di confronto incompleti",
        "comparison_deleted_balances": "Il confronto fa riferimento a bilanci eliminati. Confronto valido non disponibile.",
        "ebitda_values_not_found": "Valori EBITDA non trovati nella tabella kpi_values",
        "ebitda_zero_error": "Impossibile calcolare lo stato: EBITDA2 è zero",
        "status_calculation_error": "Errore nel calcolo dello stato: {error}",
        "no_companies_assigned": "Nessuna azienda assegnata all'utente {user}",
        "user_companies_retrieved_success": "Aziende per l'utente {user} recuperate con successo",
        "user_companies_retrieve_failed": "Recupero aziende utente fallito",
        "companies_list_retrieved_success": "Elenco aziende recuperato con successo",
        "parent_company_id_required": "ID azienda madre richiesto",
        "competitor_companies_retrieved_success": "Aziende concorrenti per l'azienda madre recuperate con successo",
        "competitor_companies_retrieve_failed": "Recupero aziende concorrenti fallito per l'azienda madre {id_company}",
        # Pre-Dashboard Service Messages
        "pre_dashboard_missing": "Record pre-dashboard mancante",
        "pre_dashboard_not_created_msg": "Il record pre-dashboard non è stato creato durante la creazione dell'azienda",
        "pre_dashboard_not_found_msg": "Record pre-dashboard non trovato per questa azienda",
        "pre_dashboard_retrieved_success": "Pre-dashboard recuperato con successo",
        "pre_dashboard_retrieve_failed": "Recupero del record pre-dashboard fallito",
        "pre_dashboard_create_failed": "Creazione del record pre-dashboard fallita",
        "pre_dashboard_update_failed": "Aggiornamento del record pre-dashboard fallito",
        "pre_dashboard_updated_success": "Pre-dashboard aggiornato con successo",
        # Balance Sheet Service Messages
        "invalid_competitor_company_msg": "Azienda concorrente non valida: manca parent_company_id",
        "competitor_access_denied_msg": "Non hai accesso a questa azienda concorrente. Devi essere assegnato alla sua azienda madre (id_company={parent_company_id}).",
        "company_access_denied_msg": "Non hai accesso all'azienda {company_id}. Puoi accedere solo alle aziende assegnate a te.",
        "unknown_user_role": "Ruolo utente sconosciuto: {user_role}",
        "year_mismatch": "Anno non corrispondente. {file_type} riporta {pdf_year} mentre il payload contiene {payload_year}.",
        "month_mismatch": "Mese non corrispondente. {file_type} riporta {pdf_month} mentre il payload contiene {payload_month}.",
        "verification_failed_msg": "Impossibile verificare i bilanci esistenti",
        "delete_failed_msg": "Impossibile eliminare il bilancio e i dati di benchmark correlati",
        "delete_existing_failed_msg": "Impossibile eliminare i bilanci esistenti: {error}",
        "file_required": "File richiesto",
        "invalid_file_type": "Sono consentiti solo file PDF, XLSX e XBRL/XML",
        "invalid_mode": "Modalità non valida: {mode}. Le modalità valide sono: pdf, xlsx, xbrl, xml, manual",
        "mode_mismatch": 'La modalità è impostata su "{mode_display}" ma il file caricato è {file_ext}. Carica un file {mode_display} o cambia la modalità.',
        "invalid_year": "Anno non valido. Deve essere compreso tra 1900 e 2100",
        "invalid_month": "Mese non valido. Deve essere compreso tra 1 e 12",
        "unknown_excel_format": "Formato Excel sconosciuto",
        "excel_script_error": "Impossibile determinare lo script corrispondente per questo file XLSX",
        "unsupported_file_type": "Tipo di file non supportato: {file_ext}",
        "extraction_error": "Errore di estrazione",
        "extraction_failed_msg": "Impossibile estrarre i dati da {file_ext}: {error}",
        "balance_sheet_exists": "Il bilancio esiste già.",
        "save_balance_failed": "Impossibile salvare il record del bilancio",
        "balance_sheet_uploaded_success": "Bilancio caricato con successo.",
        "balance_sheet_upload_failed": "Caricamento del bilancio fallito",
        "valid_company_id_required": "ID azienda valido richiesto",
        "balance_sheets_retrieve_failed": "Recupero bilanci fallito",
        "balance_sheets_retrieved_success": "Bilanci recuperati con successo",
        "valid_balance_id_required": "ID bilancio valido richiesto",
        "balance_sheet_id_not_found": "Bilancio con ID {id_balance} non trovato",
        "balance_sheet_retrieved_success": "Bilancio recuperato con successo",
        "balance_sheet_retrieve_failed": "Recupero del bilancio fallito",
        "balance_sheet_not_found": "Bilancio non trovato",
        "already_deleted": "Già eliminato",
        "balance_sheet_already_deleted": "Il bilancio è già stato eliminato",
        "balance_sheet_deleted_success": "Bilancio eliminato con successo",
        "balance_sheet_delete_failed": "Eliminazione del bilancio fallita",
        "balance_does_not_belong": "Il bilancio {id_balance} non appartiene all'azienda {company_id}",
        # Comparison Report Service Messages
        "access_denied_permission": "Accesso negato: Non hai il permesso di accedere a questa azienda",
        "balance_sheet_no_data": "Il bilancio non contiene dati",
        "balance_sheet_id_no_data": "Il bilancio {id_balance} non contiene dati",
        "kpi_calc_stored_success": "KPI calcolati e salvati con successo",
        "kpi_calc_failed": "Calcolo dei KPI fallito",
        "insufficient_balance_sheets": "Bilanci insufficienti per il confronto.",
        "comparison_report_exists": "Esiste già un report di confronto per i due bilanci più recenti",
        "comparison_report_auto_generated_success": "Report di confronto generato automaticamente con successo",
        "comparison_report_auto_generated_failed": "Impossibile generare automaticamente il report di confronto",
        "kpi_calc_uploaded_no_comparison": "KPI calcolati per il bilancio caricato. Nessun confronto generato (non negli ultimi 2 anni).",
        "comparison_report_generation_error": "Errore durante la generazione automatica del report di confronto",
        "balance_sheet_same_company_required": "Entrambi i bilanci devono appartenere alla stessa azienda",
        "failed_store_kpi_values": "Impossibile salvare i valori dei KPI",
        "failed_create_analysis": "Impossibile creare il record di analisi",
        "failed_create_report": "Impossibile creare il record del report",
        "failed_create_analysis_kpi": "Impossibile creare l'analisi KPI per l'anno {year}: {error}",
        "comparison_report_generated_success": "Report di confronto generato con successo",
        "comparison_report_generation_failed": "Generazione del report di confronto fallita",
        "comparison_reports_retrieved_success": "Report di confronto recuperati con successo",
        "comparison_reports_retrieve_failed": "Recupero dei report di confronto fallito",
        "no_balance_sheets_found": "Nessun bilancio trovato per questa azienda",
        "min_balance_sheets_required": "Sono richiesti almeno 2 bilanci per il confronto.",
        # KPI Status Services Messages
        # Synthesis
        "insufficient_historical_data": "Dati storici insufficienti per valutare l'andamento delle performance.",
        "synthesis_2_years": "L'azienda ha registrato un {direction} del {yoy} rispetto all'anno precedente.",
        "synthesis_3_years": "L'azienda ha registrato un {long_dir} del {trend} rispetto al {y0}. Rispetto all'esercizio precedente, il valore mostra un {short_dir} del {yoy}.",
        # Competitor Synthesis
        "competitor_insufficient_data": "Dati insufficienti per il confronto con i competitor.",
        "competitor_levels_similar": "Entrambe le aziende sono a livelli simili. Il {kpi_name} del competitor è {comp_val_str} mentre la media della tua azienda è {company_val_str} (negli anni {years_str}). Divario di performance: {gap}% - sostanzialmente uguale.",
        "competitor_ahead": "Il competitor è AVANTI del {ahead_by}%. Il {kpi_name} del competitor è {comp_val_str} rispetto alla media della tua azienda di {company_val_str} (negli anni {years_str}). Ciò significa che il competitor sta performando al {goal_percentage}% del livello della tua azienda. La tua azienda deve migliorare del {ahead_by}% per eguagliare il competitor.",
        "company_ahead": "La tua azienda è AVANTI del {ahead_by}%. La media del {kpi_name} della tua azienda è {company_val_str} (negli anni {years_str}) rispetto a {comp_val_str} del competitor. Il competitor sta performando al {goal_percentage}% del livello della tua azienda. La tua azienda mantiene un vantaggio competitivo del {ahead_by}%.",
        # Competitor Advice
        "competitor_advice_closely_matched": " Entrambe le aziende sono molto vicine. Concentrati sul mantenere il vantaggio competitivo e identificare opportunità di differenziazione.",
        "competitor_advice_significantly_ahead": " Il competitor è significativamente avanti ({diff}% migliore). Azione urgente richiesta: Analizza le strategie del competitor, confronta le best practice e implementa iniziative di miglioramento per colmare il divario.",
        "competitor_advice_advantage": " Il competitor ha un vantaggio ({diff}% migliore). Rivedi l'efficienza operativa, le strutture dei costi e le strategie di prezzo per migliorare la posizione competitiva.",
        "competitor_advice_balanced": " La posizione competitiva è bilanciata ({goal_percentage}% del livello del competitor). Continua a ottimizzare le operazioni per rafforzare e mantenere la posizione di mercato.",
        "competitor_advice_company_ahead": " La tua azienda è avanti ({diff}% migliore del competitor). Sfrutta questo vantaggio affrontando eventuali debolezze operative per mantenere la leadership competitiva.",
        "competitor_advice_strong_advantage": " La tua azienda ha un forte vantaggio competitivo ({diff}% migliore). Mantieni questa posizione di leadership attraverso il miglioramento continuo e l'innovazione.",
        # KPI Suggestions (EBITDA)
        "kpi_EBITDA_GOOD_suggestion": "Mantenere una forte performance operativa e continuare le attuali iniziative di efficienza.",
        "kpi_EBITDA_AVERAGE_suggestion": "Rivedere i costi operativi e migliorare l'efficienza per rafforzare la redditività.",
        "kpi_EBITDA_RISKY_suggestion": "Ridurre le spese operative e rivalutare urgentemente le strategie di prezzo.",
        "kpi_EBITDA_ALARMING_suggestion": "È necessaria una ristrutturazione immediata per ripristinare la redditività operativa.",
        # KPI Suggestions (EBIT_Reddito_Operativo)
        "kpi_EBIT_Reddito_Operativo_GOOD_suggestion": "Il reddito operativo è sano; sostenere le attuali operazioni aziendali.",
        "kpi_EBIT_Reddito_Operativo_AVERAGE_suggestion": "Migliorare l'efficienza operativa e monitorare le strutture dei costi.",
        "kpi_EBIT_Reddito_Operativo_RISKY_suggestion": "I margini operativi sono sotto pressione; sono necessarie azioni correttive.",
        "kpi_EBIT_Reddito_Operativo_ALARMING_suggestion": "Rilevate perdite operative critiche; necessario intervento immediato.",
        # KPI Suggestions (MOL_RICAVI_%)
        "kpi_MOL_RICAVI_%_GOOD_suggestion": "La creazione di valore dai ricavi è forte; mantenere la disciplina dei prezzi.",
        "kpi_MOL_RICAVI_%_AVERAGE_suggestion": "Analizzare i driver di costo per migliorare il contributo dai ricavi.",
        "kpi_MOL_RICAVI_%_RISKY_suggestion": "Basso margine sui ricavi; ottimizzare i costi di produzione e approvvigionamento.",
        "kpi_MOL_RICAVI_%_ALARMING_suggestion": "Grave erosione dei margini; necessaria revisione urgente del modello di business.",
        # KPI Suggestions (EBITDA_Margin_%)
        "kpi_EBITDA_Margin_%_GOOD_suggestion": "Il margine di redditività è forte; continuare la disciplina operativa.",
        "kpi_EBITDA_Margin_%_AVERAGE_suggestion": "Migliorare il controllo dei costi per aumentare i margini EBITDA.",
        "kpi_EBITDA_Margin_%_RISKY_suggestion": "Rilevato calo dei margini; rivalutare le strategie di costo e prezzo.",
        "kpi_EBITDA_Margin_%_ALARMING_suggestion": "Margini criticamente bassi; necessarie misure correttive immediate.",
        # KPI Suggestions (Margine_Contribuzione_%)
        "kpi_Margine_Contribuzione_%_GOOD_suggestion": "Il margine di contribuzione è sano; l'attuale strategia di prezzo è efficace.",
        "kpi_Margine_Contribuzione_%_AVERAGE_suggestion": "Monitorare i costi variabili e adeguare i prezzi se necessario.",
        "kpi_Margine_Contribuzione_%_RISKY_suggestion": "Basso margine di contribuzione; necessaria ottimizzazione dei costi.",
        "kpi_Margine_Contribuzione_%_ALARMING_suggestion": "Il margine di contribuzione è insostenibile; necessaria azione urgente.",
        # KPI Suggestions (Patrimonio_Netto)
        "kpi_Patrimonio_Netto_GOOD_suggestion": "La posizione patrimoniale è solida; mantenere la stabilità finanziaria.",
        "kpi_Patrimonio_Netto_AVERAGE_suggestion": "Monitorare le passività e rafforzare gradualmente il patrimonio netto.",
        "kpi_Patrimonio_Netto_RISKY_suggestion": "Rilevata alta leva finanziaria; considerare il rafforzamento del capitale.",
        "kpi_Patrimonio_Netto_ALARMING_suggestion": "Il patrimonio netto negativo segnala rischio di solvibilità; necessaria ricapitalizzazione urgente.",
        # KPI Suggestions (Mark_Up)
        "kpi_Mark_Up_GOOD_suggestion": "I livelli di markup sono sani; la strategia di prezzo è efficace.",
        "kpi_Mark_Up_AVERAGE_suggestion": "Rivedere i prezzi per migliorare i margini di redditività.",
        "kpi_Mark_Up_RISKY_suggestion": "Rilevato basso markup; rivalutare la struttura dei costi e i prezzi.",
        "kpi_Mark_Up_ALARMING_suggestion": "Il markup è insufficiente per sostenere le operazioni; necessaria azione immediata.",
        # KPI Suggestions (Fatturato_Equilibrio_BEP)
        "kpi_Fatturato_Equilibrio_BEP_GOOD_suggestion": "Il punto di pareggio è gestibile; la sostenibilità aziendale è forte.",
        "kpi_Fatturato_Equilibrio_BEP_AVERAGE_suggestion": "Monitorare il volume delle vendite per rimanere al di sopra del livello di pareggio.",
        "kpi_Fatturato_Equilibrio_BEP_RISKY_suggestion": "Il punto di pareggio è alto; migliorare l'efficienza dei costi o aumentare i ricavi.",
        "kpi_Fatturato_Equilibrio_BEP_ALARMING_suggestion": "Le vendite di pareggio sono insostenibili; necessaria ristrutturazione urgente.",
        # KPI Suggestions (Spese_Generali_Ratio)
        "kpi_Spese_Generali_Ratio_GOOD_suggestion": "Le spese generali sono ben controllate rispetto ai ricavi.",
        "kpi_Spese_Generali_Ratio_AVERAGE_suggestion": "Monitorare i costi generali per evitare pressione sui margini.",
        "kpi_Spese_Generali_Ratio_RISKY_suggestion": "Rilevato alto rapporto spese generali; ridurre le spese generali.",
        "kpi_Spese_Generali_Ratio_ALARMING_suggestion": "I costi generali sono eccessivi; necessario taglio dei costi immediato.",
        # KPI Suggestions (Ricavi_Totali)
        "kpi_Ricavi_Totali_GOOD_suggestion": "La crescita dei ricavi è sana; continuare le strategie di espansione.",
        "kpi_Ricavi_Totali_AVERAGE_suggestion": "Stabilizzare i ricavi ed esplorare opportunità di crescita.",
        "kpi_Ricavi_Totali_RISKY_suggestion": "Rilevato calo dei ricavi; rafforzare le vendite e gli sforzi di marketing.",
        "kpi_Ricavi_Totali_ALARMING_suggestion": "Grave contrazione dei ricavi; necessario intervento aziendale immediato.",
        # KPI Suggestions (Costi_Variabili)
        "kpi_Costi_Variabili_GOOD_suggestion": "I costi variabili sono ben gestiti rispetto alla produzione.",
        "kpi_Costi_Variabili_AVERAGE_suggestion": "Monitorare i trend dei costi variabili e l'efficienza dei fornitori.",
        "kpi_Costi_Variabili_RISKY_suggestion": "I costi variabili sono in aumento; ottimizzare l'approvvigionamento e le operazioni.",
        "kpi_Costi_Variabili_ALARMING_suggestion": "Rilevati costi variabili incontrollati; necessaria azione correttiva urgente.",
        # Health Service
        "db_connection_healthy_with_count": "Connessione al database sana (tabelle: {count})",
        "db_connection_healthy": "Connessione al database sana",
        "db_connection_failed": "Connessione al database fallita: {error}",
        "app_running_with_users": "Applicazione in esecuzione con {count} utenti",
        "app_health_check_failed": "Controllo salute applicazione fallito: {error}",
        "email_service_configured": "Servizio email configurato",
        "email_service_not_configured": "Servizio email non configurato",
        "email_service_check_failed": "Controllo servizio email fallito: {error}",
        "ai_services_configured": "Servizi AI configurati",
        "ai_services_not_configured": "Servizi AI non configurati",
        "ai_services_check_failed": "Controllo servizi AI fallito: {error}",
        "secret_key_not_configured": "SECRET_KEY non configurata correttamente",
        "jwt_secret_key_not_configured": "JWT_SECRET_KEY non configurata correttamente",
        "db_url_not_configured": "DATABASE_URL_DB non configurata",
        "external_service_check_failed": "Controllo salute servizi esterni fallito: {error}",
        "performance_metrics_failed": "Raccolta metriche prestazioni fallita: {error}",
        "health_check_failed": "Controllo salute fallito: {error}",
        # Benchmark Service
        "company_id_and_balance_required": "ID azienda e almeno un bilancio sono richiesti",
        "balance_sheet_spec_error": "Ogni bilancio deve avere 'year' e 'budgetType' (il mese è facoltativo)",
        "invalid_budget_type": "budgetType '{type}' non valido",
        "no_balance_found_with_month": "Nessun bilancio trovato per l'anno {year}, budgetType '{type}', mese {month}",
        "no_balance_found": "Nessun bilancio trovato per l'anno {year}, budgetType '{type}'",
        "benchmark_report_already_exists": "Il report di benchmark esiste già con gli stessi bilanci",
        "no_kpi_values_found": "Nessun valore KPI trovato per i bilanci selezionati",
        "benchmark_report_created": "Report di benchmark creato con successo",
        "report_not_found": "Report non trovato",
        "analysis_not_found_for_report": "Analisi non trovata per il report",
        "no_benchmarks_found_for_report": "Nessun benchmark trovato per il report",
        "benchmarks_fetched_successfully": "Benchmark recuperati con successo",
        "valid_company_id_required": "È richiesto un company_id valido",
        "no_balance_sheets_found": "Nessun bilancio trovato",
        "balance_sheet_years_retrieved": "Anni dei bilanci recuperati con successo",
        "failed_retrieve_balance_years": "Impossibile recuperare gli anni dei bilanci",
        "analysis_id_and_kpi_required": "ID analisi e nome KPI sono richiesti",
        "analysis_not_found": "Analisi non trovata",
        "no_benchmarks_found_for_analysis": "Nessun benchmark trovato per l'analisi",
        "no_kpi_info_found_for_analysis": "Nessuna info KPI trovata per l'analisi",
        "kpi_not_found_in_analysis": "KPI '{name}' non trovato nell'analisi",
        "benchmark_kpi_note_updated": "Nota KPI benchmark aggiornata con successo",
        "no_benchmark_reports_found": "Nessun report di benchmark trovato",
        "benchmark_reports_retrieved": "Report di benchmark recuperati con successo",
        "report_id_required": "Il report_id è richiesto",
        "no_analysis_kpi_infos_found": "Nessuna info analisi KPI trovata per il report",
        "benchmark_deleted_with_competitors": "Report di benchmark e {count} report del concorrente eliminati con successo",
        "benchmark_deleted_successfully": "Report di benchmark eliminato con successo",
        "parent_report_id_required": "parent_report_id è richiesto",
        "competitor_id_required": "competitor_id è richiesto",
        "year_required": "l'anno è richiesto",
        "balancesheet_name_required": "il nome del bilancio è richiesto",
        "parent_benchmark_not_found": "Report di benchmark principale non trovato",
        "parent_analysis_not_found": "Analisi principale non trovata",
        "no_balances_found_in_parent": "Nessun bilancio trovato nel benchmark principale",
        "main_company_balance_not_found": "Bilancio dell'azienda principale non trovato",
        "invalid_competitor_for_company": "Concorrente non valido per questa azienda",
        "competitor_balance_not_found": "Bilancio del concorrente non trovato",
        "competitor_benchmark_already_exists": "Questo report di benchmark del concorrente esiste già",
        "competitor_benchmark_created": "Report di confronto del concorrente creato con successo",
        "competitor_benchmarks_fetched": "Report di benchmark del concorrente recuperati con successo",
        "competitor_companies_retrieved_success": "Aziende competitor recuperate con successo",
        "competitor_companies_retrieved_failed": "Impossibile recuperare le aziende competitor",
        "failed_retrieve_competitors": "Impossibile recuperare i competitor suggeriti",
        "competitor_already_added_to_benchmark": "Questo bilancio del competitor è già stato aggiunto a questo rapporto benchmark",
        # Monitoraggio Predittivo & Suggerimenti
        "pred_sug_ricavi_cause": "Analizza le cause della riduzione per capire se è un problema temporaneo o strutturale.",
        "pred_sug_ricavi_pricing": "Rivedi la strategia di pricing: Considera prezzi differenziati per clienti premium o servizi express.",
        "pred_sug_ricavi_costi_diretti": "La redditività rispetto ai costi diretti è bassa, potrebbe essere necessario rivedere i prezzi o ridurre i costi operativi.",
        "pred_sug_ricavi_mercati": "Espanditi in nuovi mercati: Se lavori su ristrutturazioni residenziali, potresti valutare il settore commerciale o industriale.",
        "pred_sug_ricavi_fidelizzazione": "Fidelizza i clienti esistenti: Offri incentivi, sconti per clienti abituali e programmi di fidelizzazione.",
        "pred_sug_ricavi_incasso": "Rivedi il tempo medio di incasso.",
        "pred_sug_roi_efficiency": "Analizza l'efficienza dell'allocazione del capitale per migliorare il ritorno sugli investimenti.",
        "pred_sug_roi_turnover": "Migliora la rotazione degli asset ottimizzando la gestione delle scorte e i tempi di incasso.",
        "pred_sug_roe_leverage": "Rivaluta la struttura del capitale per ottimizzare l'equilibrio tra debito e patrimonio netto.",
        "pred_sug_roe_profitability": "Focus sul miglioramento del margine netto attraverso l'ottimizzazione dei costi.",
        "pred_sug_ros_margins": "Monitora i costi di produzione e i servizi per migliorare i margini sulle vendite.",
        "pred_sug_ros_mix": "Analizza il mix di prodotti/servizi per spingere le offerte a maggior margine.",
        "pred_sug_ebitda_opex": "Riduci i costi operativi fissi e rinegozia i contratti con i fornitori.",
        "pred_sug_ebitda_productivity": "Aumenta la produttività del personale e ottimizza i processi interni.",
        "pred_sug_mdc_variable": "Controlla rigorosamente i costi variabili e gli sprechi di produzione.",
        "pred_sug_mdc_volume": "Aumenta i volumi di vendita per assorbire meglio i costi fissi.",
        # Suggerimenti Nuovi e Granulari (IT)
        "pred_sug_ricavi_cross_selling": "Implementa strategie di cross-selling e up-selling sui clienti esistenti.",
        "pred_sug_ricavi_digital_marketing": "Investi in campagne di digital marketing mirate per aumentare la visibilità.",
        "pred_sug_ricavi_partnership": "Valuta partnership strategiche per accedere a nuovi segmenti di clientela.",
        "pred_sug_roi_low_performing": "Identifica e dismetti gli asset o i rami d'azienda a bassa redditività.",
        "pred_sug_roi_reinvestment": "Valuta il reinvestimento degli utili in tecnologie ad alta efficienza operativa.",
        "pred_sug_roi_working_capital": "Ridimensiona l'attivo circolante per liberare risorse finanziarie.",
        "pred_sug_roe_refinancing": "Rinegozia le condizioni del debito per ridurre gli oneri finanziari.",
        "pred_sug_roe_equity_structure": "Ottimizza il mix tra capitale proprio e debito per massimizzare il rendimento.",
        "pred_sug_roe_dividend_policy": "Rivedi la politica dei dividendi per bilanciare autofinanziamento e rendimento.",
        "pred_sug_ros_premium_price": "Punta a un posizionamento premium per giustificare margini più elevati.",
        "pred_sug_ros_cost_control": "Implementa un monitoraggio analitico dei costi diretti per linea di prodotto.",
        "pred_sug_ros_discount_policy": "Rivedi la politica degli sconti per evitare l'erosione eccessiva dei margini.",
        "pred_sug_ebitda_energy": "Investi in efficienza energetica per ridurre i costi fissi di struttura.",
        "pred_sug_ebitda_outsourcing": "Valuta l'outsourcing di attività non core per rendere più flessibili i costi.",
        "pred_sug_ebitda_digitalization": "Digitalizza i processi per ridurre i costi operativi e amministrativi.",
        "pred_sug_mdc_supplier_nego": "Rinegozia le condizioni di acquisto con i principali fornitori.",
        "pred_sug_mdc_waste_reduction": "Implementa protocolli lean production per ridurre sprechi e scarti.",
        "pred_sug_mdc_logistics": "Ottimizza logistica e trasporti per ridurre l'impatto dei costi variabili.",
        "pred_sug_gen_consolidation": "Continua il monitoraggio trimestrale per consolidare i risultati.",
        "pred_sug_gen_scalability": "Valuta modelli di business più scalabili per sostenere la crescita futura.",
        "pred_sug_gen_innovation": "Investi in Ricerca e Sviluppo per mantenere il vantaggio competitivo.",
        "pred_no_complete_balances": "Nessun bilancio annuale completo (finale) trovato da utilizzare come base per la previsione.",
        "pred_no_historical_trend": "Impossibile identificare il trend storico dai bilanci completi.",
        "pred_prediction_success": "Previsione generata con successo",
    },
}


def get_message(key: str, locale: str = "en", **kwargs) -> str:
    """
    Get localized message for the given key and locale.

    Args:
        key (str): The message key
        locale (str): 'en' or 'it' (default 'en')
        **kwargs: Format arguments for the string

    Returns:
        str: Localized message
    """
    # Normalize locale (only support en/it for now, default to en)
    if not locale:
        locale = "en"

    # Handle composite locales like 'it-IT' or 'en-US' or 'it,en;q=0.9'
    # Simple strategy: take the first 2 characters if they match a supported language
    normalized_locale = locale[:2].lower()
    if normalized_locale in MESSAGES:
        locale = normalized_locale
    elif locale not in MESSAGES:
        locale = "en"

    # Get message or fallback to English, then to key
    msg = MESSAGES[locale].get(key, MESSAGES["en"].get(key, key))

    # Format if arguments provided
    if kwargs:
        try:
            return msg.format(**kwargs)
        except Exception:
            return msg
    
    return msg
